[tools]
"gem:kamal" = "latest"
mprocs = "latest"
node = "18"
"npm:figlet" = "latest"
"ubi:adwinying/php" = "8.2"
"ubi:composer/composer" = "latest"

[hooks]
enter = """
figlet hotel-hamlet
echo "$(composer --version)"
echo "node: $(node --version)"
echo "npm: v$(npm --version)"
"""

[tasks.backend]
description = "Start backend dev server"
run = "php artisan serve --host 0.0.0.0 --port 8080"

[tasks.frontend]
description = "Start frontend dev server"
run = "npm run dev"

[tasks.webdev]
description = "Start app dependencies"
dir = "../webdev"
run = "docker compose up -d mysql8"

[settings]
experimental = true
