version: "0.5"

processes:
  php-fpm:
    command: "envsubst '' < .environment/templates/php-fpm.conf > .environment/runtime/php-fpm.conf && php-fpm -F -y ./.environment/runtime/php-fpm.conf"
    availability:
      restart: always
      max_restarts: 5

  nginx:
    command: "envsubst '' < .environment/templates/nginx.conf > .environment/runtime/nginx.conf && nginx -e /dev/stderr -c $PWD/.environment/runtime/nginx.conf"
    depends_on:
      php-fpm:
        condition: process_started
    availability:
      restart: always
      max_restarts: 5

  frontend:
    command: "npm run dev -- --host"
    depends_on:
      nginx:
        condition: process_started
